package common.bean;

public enum OperationType {
    USER_ADD, USER_REMOVE, END_MEETING, HOST_CHANGE, MANAGER_ADD, CHAT_MESSAGE,
    MANAGER_REMOVE, VIDEO_ON, VIDEO_OFF, VIDEO_CLOSE, AUDIO_ON, AUDIO_OFF;
}
